export default {
  // generated from APIs
  HEADER21: "Other Options",
  "99813A": "Ship-Thru: Ground Effects - Sterling Heights",
  "29V": "Customer Preferred Package 29V",
  ST2: "Premium Sunrider Black Soft Top",
  HEADER29: "Internal Options",
  HEADER04: "Transmissions",
  WARANT: "FCA 5 yr/100,000 Mile Powertrain Limited Warranty",
  CT9: "Windshield Tie-Down Strap by Mopar®",
  D5: "Rubicon Cloth Bucket Seats",
  AJB: "Dual Door Group with Base Uppers",
  XWX: "Jeep Trail-Rated Kit",
  NNC: "Snorkel by Mopar®",
  HEADER32: "Internal Options",
  PHT_02: "Limited Edition Reign Exterior Paint",
  CS2: "Freedom Panel Storage Bag",
  CVW: "Leather-Wrapped Shift Knob",
  HEADER15: "Additional Interior Features",
  JPM: "Heated Front Seats",
  "99823A": "Ship-Thru: Ground Effects - Warren",
  CLP: "Black Door Sill Guards by Mopar®",
  "99862A": "Ship-Thru: Masterack - Dundalk",
  GER: "Removable Rear Quarter Windows",
  PX8_02: "Black Clear-Coat Exterior Paint",
  HEADER26: "Internal Options",
  HEADER07: "Wheels",
  "99870A": "Ship-Thru: Knapheide - Baltimore",
  "99846A": "Ship-Thru: Dejana Cargo & Van Body Mfg - Saltillo",
  "99828A": "Ship-Thru: INLAD Truck & Van - District Heights",
  HT3: "Body-Color Freedom Top® 3-Piece Hard Top",
  "99815A": "Ship-Thru: OEM - Saltillo",
  STJ: "Sky One-Touch® Power-Top",
  STB: "Premium Black Sunrider® Soft Top",
  FINAL1: "Fleet Final Order Date: TBD",
  HEADER37: "Other Options",
  HEADER10: "Entertainment",
  MD6: "Steel Rear Bumper",
  HEADER18: "Roof Racks & Rails",
  "99833A": "Ship-Thru: Knapheide - Saltillo",
  CS7: "Mesh Sunbonnet Top by Mopar®",
  PDN_02: "Sting-Gray Clear-Coat Exterior Paint",
  PSE_01: "Silver-Zynith Exterior Paint",
  NAS: "50 State Emissions",
  "99803A": "Ship-Thru: Adrian Steel - Saltillo",
  "99821A": "Ship-Thru: NBC - Roseville",
  "99864A": "Ship-Thru: Ground Effects",
  AJS: "Dual Door Group with Premium Uppers",
  "99818A": "Ship-Thru: Reading - Saltillo",
  TV_01: "Black / Dark Saddle Interior Colors",
  "99800A": "Ship-Thru: Auto Truck Group - Maple Shade",
  NHS: "Heated Steering Wheel",
  HEADER27: "Internal Options",
  HEADER02: "Upper Level Packages",
  CSV: "Interior Assist Handles by Mopar®",
  LH2: "4 Programmable Auxiliary Switches",
  HEADER51: "Primary Colors",
  "99835A": "Ship-Thru: Masterack - Saltillo",
  UAQ: 'Radio: Uconnect 4C Nav w/8.4" Display',
  GFA: "Rear Window Defroster",
  "99852A": "Ship-Thru: Reading - Pontiac",
  HEADER30: "Internal Options",
  HEADER38: "Fleet Options",
  SCV: "Leather Wrapped Steering Wheel",
  HEADER13: "Load & Towing Groups",
  AL: "Leather-Trimmed Bucket Seats",
  PGG_02: "Sarge Green Clear-Coat Exterior Paint",
  XDB: "Hinge-Gate Reinforcement by Mopar®",
  "99892A": "Ship-Thru: Knapheide - Chicago",
  HEADER24: "Internal Options",
  MDA: "Front License Plate Bracket",
  HEADER05: "Other(s)",
  CSQ: "Rear Grab Handles by Mopar®",
  LFR: "Doors-Off Mirror Kit by Mopar®",
  "99807A": "Ship-Thru: Utilimaster",
  PW7_01: "Bright White Clear-Coat Exterior Paint",
  "99841A": "Ship-Thru: Monroe",
  CLN: "MOPAR Door Sill Guards",
  "99811A": "Ship-Thru: Midway - Saltillo",
  MHV: "Body-Color Rubicon Highline Flare",
  GMA: "Windshield with Corning® Gorilla® Glass",
  HEADER35: "Bumpers & Fascias",
  XNY: "Forward-Facing TrailCam",
  ALP: "Adaptive Cruise Control/Fwd Collision Warning Plus",
  START1: "Start-Up Date: TBD",
  HEADER16: "Sunroofs",
  XF2: "7- and 4-Pin Wiring Harness",
  CB5: "Power Top Quarter Window Storage Bag",
  DFY: "8-Speed Automatic 8P75PH PHEV Transmission",
  VEH: "Base Vehicle Price (WSJH75)",
  SDD: "Performance Suspension",
  CHD: "Hardtop Headliner by Mopar®",
  GCH: "Half Doors with Uppers",
  PJF_02: "(0 P) High Velocity Clearcoat",
  M9G: "Lower Body Side Graphic by Mopar®",
  HEADER25: "Internal Options",
  ADH: "Trailer-Tow and Heavy-Duty Electrical Group",
  HEADER08: "Seat Types",
  CBS: "Black Stitched Leather Upgrade by Mopar®",
  PGP_02: "Earl Clear-Coat Exterior Paint",
  "99822A": "Ship-Thru: Canfield - Dundalk",
  CK5: "Cargo Tub Liner by Mopar®",
  "99839A": "Ship-Thru: Midway - Elkhart",
  "99849A": "Ship-Thru: Masterack - Pontiac",
  HEADER36: "Grilles",
  HEADER11: "Packages & Equipment Groups",
  HT1: "Black Freedom Top® 3-Piece Hard Top",
  PBJ_02: "Hydro Blue Pearl-Coat Exterior Paint",
  DEST: "Destination Surcharge (Hawaii)",
  DMF: "4.10 Axle Ratio",
  XPW: "RV Tow Harness by Mopar®",
  HEADER19: "Interior Design",
  "99840A": "Ship-Thru: OEM - Dundalk",
  CWJ: "Soft Top Window Storage Bag",
  XBM: "Remote-Start System",
  "99814A": "Ship-Thru: INLAD Truck & Van - Lombard",
  HEADER22: "Fleet Options",
  MC6: "Steel Front Bumper",
  ECX: "2.0L I4 DOHC DI Turbo PHEV Engine",
  "99802A": "Ship-Thru: Auto Truck Group - Fort Wayne",
  CVP: "Leather-Wrapped Park-Brake Handle",
  HEADER03: "Engine",
  BGG: "Advanced Brake Assist",
  "99832A": "Ship-Thru: Kerr Industries",
  "99845A": "Ship Thru: Ground Effects - Windsor",
  XAA: "ParkSense Rear Park Assist System",
  XAN: "Blind Spot & Cross Path Detection",
  HEADER33: "Internal Options",
  LMS: "Auto High Beam Headlamp Control",
  "99820A": "Ship-Thru: Dejana Cargo & Van Body Mfg - Baltimore",
  CS3: "Solid Sunbonnet Top by Mopar®",
  HEADER14: "Floor Mats",
  TT4: "LT285/70R17C OWL Off-Road Tires",
  JEK: "Premium Wrapped Instrument Panel Bezels",
  "99847A": "Ship-Thru: OEM - Warren",
  XC3: "Grab Handle Kit by Mopar®",
  "99816A": "Ship-Thru: Ranger Design",
  NH3: "Adaptive Cruise Control w/Stop",
  CWA: "All-Weather Slush Mats by Mopar®",
  BUILD: "Build-Out Date: TBD",
  CBQ: "Black Perforated Leather Upgrade by Mopar®",
  HEADER23: "Fleet Options",
  HEADER06: "Tires",
  ST8: "No Soft Top",
  APA: "Monotone Paint",
  CBF: "Premium Door Trim Panel",
  "99801A": "Ship-Thru: Auto Truck Group - Bartlett",
  HEADER34: "Internal Options",
  MHW: "Sunrider® for Hardtop by Mopar®",
  "99836A": "Ship-Thru: Knapheide - Flint",
  WEF: "17-Inch x 7.5-Inch Machined Wheels w/ Black Pockets",
  HEADER17: "Exterior Design",
  "99819A": "Ship-Thru: Canfield - Warren",
  "99896A": "Ship-Thru: Utilimaster PDI",
  GCG: "Half Doors without Uppers",
  Z1T: "GVW Rating - 6,400 Pounds",
  TXA: "LT285/70R17C BSW Off-Road Tires",
  AEN: "Dual-Top Group",
  AJ1: "Jeep® Active Safety Group",
  M9F: "Upper Body Side Graphic by Mopar®",
  HEADER20: "General Info",
  HEADER28: "Internal Options",
  HEADER01: "Emissions",
  XFN: "Class II Receiver Hitch",
  HEADER09: "Suspension",
  LSU: "Full Speed Forward Collision Warning Plus",
  HEADER50: "Interior Colors",
  PAU_02: "Granite Crystal Metallic Clear-Coat Exterior Paint",
  "99891A": "Ship-Thru: Canfield",
  X9_01: "Black Interior Color",
  BCV: "700-Amp Maintenance-Free Battery",
  HEADER31: "Internal Options",
  AJG: "Dual Door Group (Lowers Only)",
  AST: "Steel-Bumper Group",
  "99898A": "Ship-Thru: Action Truck & Body Equipment",
  JHB: "Rear Window Wiper / Washer",
  "99868A": "Ship-Thru: Adrian Steel - Baltimore",
  HEADER12: "Entertainment Components",
  PRC_02: "Firecracker Red Clear-Coat Exterior Paint",
  ORDER1: "Initial Order Date: TBD",
  ADE: "Cold Weather Group",
  "99838A": "Ship-Thru: ABS Storage Products",
  MHJ: "Satin Black Grille by Mopar®",
  WJR: "18-Inch x 8.0-Inch Fully-Painted Alum Wheels",
  XPS: "Intersection Collision Assist System",
  GX5: "Door and Liftgate Passive Entry",
  XH4: "ParkSense® Front and Rear Park-Assist with Stop",
  WHG: "18-Inch x 7.5-Inch Polished Wheels with Gray Spokes",
  GNZ: "Automatic-Dimming Exterior Driver Mirror",
  MRT: "Chrome Tubular Side Steps by Mopar®",
  MHP: "Gloss-Black Exterior Accents",
  RFX: "Wireless Charging-Pad",
  UBN: "Uconnect® 5 Nav with 10.1-Inch Touch Screen Display",
  SDB: "Heavy Duty Suspension",
  DLE: "3.70 Rear Axle Ratio",
  ABR: "Heavy-Duty Trailer-Tow Package",
  ALC: "Carbide Appearance Package",
  JHC: "Rain-Sensitive Windshield Wipers",
  X7_01: "Global Black Interior Color",
  PXJ_02: "Diamond Black Crystal Pearl-Coat Exterior Paint",
  GF1: "2nd-Row Manual Window-Shades",
  PHC_02: "Ember Pearl-Coat Exterior Paint",
  AV1: "Rear-Seat Entertainment Group",
  ACX: "Finishing Package by Mopar®",
  MWE: "Black / Gloss-Black Roof Rails",
  GRG: "Digital Rear-View Mirror",
  B6: "Capri Vinyl Seats",
  DL: "Capri Leather Seats",
  XPG: "MOPAR Paint Protection Film",
  TFB: "265/60R18 BSW All-Season LRR Tires",
  MRU: "Black Tubular Side Steps by Mopar®",
  LEW: "Memory Steering Column",
  PFJ_02: "Rocky Mountain Pearl-Coat  Exterior Paint",
  SES: "Rear Load Leveling Suspension",
  JHE: "Rear Back-Up Camera Washer",
  SUB: "Power Tilt / Telescope Steering Column",
  RTC: "Video USB Port",
  Z1D: "GVW Rating - 6,450 Pounds",
  JKJ: "Automatic Headlamp Leveling System",
  MEJ: "MOPAR Rear Splash Guards",
  XFH: "Class IV Receiver Hitch",
  WHF: "20-inch x 8.5-Inch Gloss-Black Painted Alum Wheels",
  MKM: "MOPAR Front Splash Guards",
  W7_02: "Global Black / Wicker Beige Interior Colors",
  PAS_02: "Baltic-Gray Metallic Clear-Coat Exterior Paint",
  TLP: "265/50R20 BSW All-Season LRR Tires",
  AJW: "Luxury Tech Group II",
  CAJ: "Ventilated Front Seats",
  XAK: "360 Surround-View Camera",
  "27F": "Customer Preferred Package 27F",
  RHH: "10.1-Inch Rear Entertainment Screens",
  XRW: "Amazon Fire TV Built-In",
  D6: "Capri Vinyl w/Axis II Seats",
  PCQ_02: "Midnight Sky Exterior Paint",
  PRV_02: "Velvet Red Pearl-Coat Exterior Paint",
  HEADER52: "Internal Options",
  PW7: "Bright White Clear-Coat Exterior Paint/Black Clear-Coat Exterior Paint",
  PSE: "Silver-Zynith Exterior Paint/Black Clear-Coat Exterior Paint",
  APP: "Two-Tone Paint Group",
  QX8_01: "Black Clear-Coat Exterior Paint",
  GWJ: "Dual-Pane Panoramic Sunroof",
  WBD: "18-Inch x 8.0-Inch Machined Face/Painted Alum Whls",
  JK2: "Hands-Free Power Liftgate",
  E6: "Capri Leather / Suede Seats",
  RJA: "Front Passenger Interactive Display",
  HEADER54: "Internal Options",
  PBJ: "Hydro Blue Pearl-Coat Exterior Paint/Black Clear-Coat Exterior Paint",
  HEADER53: "Internal Options",
  TMW: "265/60R18 BSW A/S All-Terrain Tires",
  XNT: "Night Vision w/ Pedestrian and Animal Detection",
  PAS: "Baltic-Gray Metallic Clear-Coat Exterior Paint/Black Clear-Coat Exterior Paint",
  ADK: "Advanced ProTech Group II",
  PCQ: "Midnight Sky Exterior Paint/Black Clear-Coat Exterior Paint",
  MMU: "Heavy-Duty Rock Slider with Step Assist by Mopar®",
  "27K": "Customer Preferred Package 27K",
  AFB: "Luxury Tech Group III",
  X7_02: "Global Black Interior Color",
  BNK: "Selec-Speed® Control",
  RTB: "SiriusXM Traffic Plus",
  HEADER43: "Internal Options",
  RSK: "1-Year SiriusXM Guardian Trial",
  ACB: "Willys Package",
  BA8: "Delete Alternator",
  JJA: "Cigar Lighter",
  MP8: "Delete 4-Wheel Drive Swing Gate Decal",
  GTB: "Power-Heated Mirrors",
  LMG: "Automatic Headlamps",
  MW7: "Black Grille",
  JFF: "Cold Air Intake System by Mopar®",
  RF7: "USB Host Flip",
  JMA: "Air Filtering",
  JLP: "GPS Antenna Input",
  DEM: "6-Speed Manual Transmission",
  GXD: "Front Door Locks 2-Door Passive Entry",
  RTF: "Integrated Center-Stack Radio",
  RTQ: "4G LTE Wi-Fi Hot Spot",
  MS3: "4-Wheel Drive Decal",
  X9M: "5-Year SiriusXM Traffic Service",
  JA8: "Off-Road Info Pages",
  MBU: "Premium Front Bumper with Gloss-Black Accents",
  GNC: "Sun Visors with Illuminated Vanity Mirrors",
  DSA: "Trac-Lok® Anti-Spin Rear Differential",
  A7: "Cloth Bucket Seats",
  BC1: "Auxiliary Battery",
  JLN: "GPS Navigation",
  RFL: '8.4" Touchscreen Display',
  HEADER44: "Internal Options",
  "23K": "Customer Preferred Package 23K",
  HEADER45: "Internal Options",
  NHA: "Engine Oil Cooler",
  JPY: "Power Windows with Front 1-Touch Down",
  NH1: "Enhanced Adaptive Cruise Control",
  HEADER39: "Fleet Options",
  MT6: "Willys Hood Decal",
  BRY: "Anti-Lock 4-Wheel Disc Brakes",
  XHZ: "Stop / Start Dual Battery System",
  DLK: "3.45 Overall Top Gear Ratio",
  CUK: "Removable Ash Tray",
  UAG: "Uconnect® 4 with 7.0-Inch Touch Screen Display",
  ERG: "3.6L V6 24V VVT eTorque Engine with Stop/Start",
  JPH: "Speed-Sensitive Power-Locks",
  AWS: "Smoker's Group",
  RF5: "Google Android Auto™",
  X9N: "5-Year SiriusXM Travel Link Service",
  "22K": "Customer Preferred Package 22K",
  HEADER40: "Internal Options",
  EC1: "2.0L I4 DOHC DI Turbo Engine with Stop/Start",
  RFP: "Apple CarPlay®",
  DRZ: "3rd Generation Dana® Solid Rear Axle",
  Z1H: "GVW Rating - 5,000 Pounds",
  TTK: "32-Inch LT255/75R17C Mud-Terrain Tires",
  BC2: "600-Amp Maintenance Free Battery",
  LPX: "LED Premium Reflector Headlamps",
  WJP: "17-Inch x 7.5-Inch Moab Black Aluminum Wheels",
  HEADER41: "Internal Options",
  XJG: "Non-Lock Fuel Cap without Discriminator",
  HAB: "Air Conditioning w/Auto Temp Control",
  LSA: "Security Alarm",
  RSD: "SiriusXM Satellite Radio",
  BAJ: "220 Amp Alternator",
  LNV: "Front LED Fog Lamps",
  AAS: "Sport S",
  HEADER46: "Internal Options",
  LAY: "LED Taillamps",
  T5_01: "Black / Heritage Tan Interior Colors",
  DFT: "8-Speed Automatic 850RE Transmission",
  ERC: "3.6L V6 24V VVT Engine with Stop/Start",
  HEADER47: "Internal Options",
  SDA: "Normal-Duty Suspension",
  XRB: "Integrated Voice Command",
  XGD: "Universal Garage Door Opener",
  BAL: "240-Amp Alternator",
  RSR: "Emergency/Assistance Call",
  RE8: "HD Radio",
  GNK: "Rear View Auto Dim Mirror",
  SCJ: "Premium Wrapped Steering Wheel",
  MBC: "Injection Molded Black Rear Bumper",
  XBZ: "48-Volt Belt Starter Generator",
  GCD: "Deep-Tint Sunscreen Windows",
  GXM: "Remote Keyless-Entry",
  MEF: "Rock Protection Sill Rails",
  Z5N: "GVW Rating - 5,050 Pounds",
  "25K": "Customer Preferred Package 25K",
  RSM: "SiriusXM Travel Link",
  JAJ: 'Cluster 7.0" TFT Color Display',
  HEADER42: "Internal Options",
  DJV: "3rd Generation Heavy-Duty Dana® 44 Front Axle",
  HEADER49: "Internal Options",
  Z1K: "GVWR: 5,400 lbs",
  DJE: "3rd Generation Heavy-Duty Dana® 44 Front Axle",
  MMZ: "Mold-In-Color Rubicon Highline Flare",
  HEADER48: "Internal Options",
  DFV: "8-Spd Automatic 8HP75 Transmission",
  AGB: "Xtreme Recon 35-Inch Tire Package",
  XAL: "Selective Catalytic Reduction (UREA)",
  XJ4: "Non-Locking Fuel Cap with Discriminator",
  LMX: "Daytime Running Lamp System",
  MPG: "Diesel 3.0L Hood Graphic by Mopar®",
  SDG: "35-Inch Tire Suspension",
  Z5P: "GVW Rating - 5,460 Pounds",
  XFP: "Tire Relocation Kit by Mopar®",
  NLA: "Wheel Flare Extensions",
  Z1L: "GVW Rating - 5,900 Pounds",
  DS7: "Conventional Differential Front Axle",
  DRF: "Dana M220 Wide Rear Axle",
  Z1F: "GVW Rating - 7,650 Pounds",
  DMU: "4.56 Rear Axle Ratio",
  DME: "3.73 Axle Ratio",
  MZR: "Gray EcoDiesel Badge",
  DHP: "Selec-Trac® Full Time 4WD System",
  RS3: "Remote USB Port - Charge-Only",
  JKV: "115V Auxiliary Power Outlet",
  EXJ: "3.0L V6 Turbo Diesel Engine with Stop/Start",
  LPY: "Daytime Running Lamps LED Accents",
  NGA: "18.3-Gallon Fuel Tank",
  "26K": "Customer Preferred Package 26K",
  LDB: "Console Bin Task Light",
  WFC: "17-Inch x 8.0-Inch Beadlock-Capable Wheel",
  TVC: "LT315/70R17C 113/110S Tires",
  RS2: "Media Hub w/2 Charge Only USBs",
  BR4: "Performance Anti-Lock 4-Wheel Disc Brakes",
  XJN: "Black Fuel-Filler Door",
  CXK: "Jack Spacer by Mopar®",
  AGS: "Sun and Sound Package",
  "25S": "Customer Preferred Package 25S",
  AEK: '8.4" Radio & Premium Audio Group',
  XJD: "Black Fuel-Filler Door by Mopar®",
  RC4: "Alpine Premium Audio System",
  TTC: "245/75R17 BSW All-Terrain Tires",
  WGG: "17-Inch x 7.5-Inch Machined Granite Crystal Wheels",
  AAN: "Technology Group",
  ADC: "Convenience Group",
  M9E: "1941 Hood Decal by Mopar®",
  HEADER55: "Internal Options",
  XJB: "Chrome Fuel-Filler Door by Mopar®",
  WF9: "17-Inch x 7.5-Inch Tech Silver Aluminum Wheels",
  M9D: "Hood Decal with American Flag by Mopar®",
  "23S": "Customer Preferred Package 23S",
  ADA: "LED Headlamp and Fog Lamp Group",
  "26S": "Customer Preferred Package 26S",
  TQJ: "245/75R17 All-Season Tires",
  "22S": "Customer Preferred Package 22S",
  MRK: "Side Steps",
  AGB_: 'Xtreme Recon 35" Tire Package',
  "25B": "Customer Preferred Package 25B",
  "23B": "Customer Preferred Package 23B",
  WD2: "17-Inch x 7.5-Inch Black Steel Styled Wheels",
  "22B": "Customer Preferred Package 22B",
  "26B": "Customer Preferred Package 26B",
  "23W": "Customer Preferred Package 23W",
  TTP: "LT255/75R17C Tires",
  "22W": "Customer Preferred Package 22W",
  "25W": "Customer Preferred Package 25W",
  "26W": "Customer Preferred Package 26W",
  MVA: "Gray/Black Trail Rated Badge",
  MZG: "Gloss Black Limited Badge",
  "22N": "Customer Preferred Package 22N",
  WRN: "20-Inch x 8.0-Inch Gloss Black Aluminum Wheels",
  MNK: "Body-Color Door & Tailgate Handles",
  Z1E: "GVW Rating - 7,600 Pounds",
  "26N": "Customer Preferred Package 26N",
  MW2: "Chrome EcoDiesel Badge",
  MMT: "Full Body Color Fender Flares",
  TA_02: "Black / Steel Gray Interior Colors",
  MBP: "Body Color Front Bumper",
  MFK: "Body Color Grille w/Gloss Black Rings",
  "25N": "Customer Preferred Package 25N",
  MBQ: "Body Color Rear Bumper w/Step Pads",
  AD6: "Premium LED Lighting Group",
  AHN: "High Altitude Package",
  KL: "Quilted Nappa Leather-Trimmed Bucket Seats",
  JEN: "Wrapped Instrument Panel Bezel with Caramel Stitch",
  XSN: "Caramel Interior Accents",
  TTG: "275/55R20 BSW All-Season Tires",
  BR5: "Anti-Lock 4-Wheel FNC Disc Brakes",
  SDE: "Sport Suspension",
  Z5H: "GVW Rating - 5,550 Pounds",
  MYN: "Summit Badging",
  XGJ: "Premium Dark Exterior Accents",
  LEB: "Exterior Mirrors w/Supplemental Signals",
  XJ8: "Body Color Fuel Filler Door",
  CL: "Nappa Leather Seats",
  WGB: "18-Inch x 7.5-Inch Tech-Gray Machined-Face Wheels",
  TDA: "255/70R18 All-Season Tires",
  "25G": "Customer Preferred Package 25G",
  TRR: "255/70R18 All-Terrain Tires",
  T7: "Cloth Low-Back Bucket Seats",
  "22G": "Customer Preferred Package 22G",
  SDU: "Heavy-Duty Suspension with Gas Shocks",
  "26G": "Customer Preferred Package 26G",
  TWG: "33-Inch LT285/70R17C Mud-Terrain Tires",
  SDF: "35-Inch Tire Rubicon 392 Suspension",
  HD: "Leather-Trimmed Bucket Seats",
  Z1M: "GVW Rating - 6,100 Pounds",
  Z1U: "GVW Rating - 6,250 Pounds",
  ESG: "6.4L V8 Engine",
  NAA: "Federal Emissions",
  WF2: "17-Inch x 8.0-Inch Bronze Beadlock-Capable Wheel",
  WGU: "17-Inch x 7.5-Inch Beadlock-Capable Wheels",
  "27X": "Customer Preferred Package 27X",
  SDH: "Rubicon 392 Suspension",
  "22A": "Customer Preferred Package 22A",
  TQL: "245/75R17 All-Terrain Tires",
  XJE: "Body Color Power Locking Fuel Filler Door",
  MWS: "Gray/Blue Trail Rated Badge",
  "29N": "Customer Preferred Package 29N",
  Z1S: "GVW Rating - 6,200 Pounds",
  WRF: "20-Inch x 8.0-Inch Fully Painted Aluminum Wheels",
  MSL: "Gray/Blue Jeep Badge",
  WRG: "20-Inch x 8.0-Inch Fully-Painted Aluminum Wheels",
  "29P": "Customer Preferred Package 29P",
  AAM: "Luxury Tech Group IV",
  JWJ: "12-Way Power Adjustable Front Passenger Seat",
  LE5: "Passenger Seat Memory",
  HAL: "A/C with 4-Zone Automatic Temperature Control",
  PRV_03: "Velvet Red Pearl-Coat Exterior Paint",
  PAS_03: "Baltic Gray Metallic Clear-Coat Exterior Paint",
  "27P": "Customer Preferred Package 27P",
  PFJ: "Rocky Mountain Pearl-Coat  Exterior Paint/Black Clear-Coat Exterior Paint",
  XEF: "Transfer-Case Skid-Plate Shield",
  JBA: "Map-In-Cluster Display",
  CE9: "Power Driver Seat with Back-Massager",
  DSF: "Electronic Rear Limited-Slip Differential",
  LBK: "Head-Up Display",
  ADN: "Advanced ProTech Group III",
  PCQ_03: "Midnight Sky Exterior Paint",
  SCC: "Leather-Wrapped Steering Wheel",
  PBJ_03: "Hydro Blue Pearl-Coat Exterior Paint",
  PFJ_03: "Rocky Mountain Pearl-Coat Exterior Paint",
  WLJ: "20-Inch x 8.5-Inch Machined Face Aluminum Wheels",
  MXS: "Black Roof",
  PW7_02: "Bright White Clear-Coat Exterior Paint",
  PRV: "Velvet Red Pearl-Coat Exterior Paint/Black Clear-Coat Exterior Paint",
  JVJ: "12-Way Power Adjustable Driver Seat",
  PSE_02: "Silver Zynith Exterior Paint",
  BL: "Nappa Leather-Trimmed Seats with Massage",
  TL: "Nappa Leather Seats",
  MT2: '"Trail-Rated" Badge',
  TKJ: "265/50R20 BSW All-Season LRR Tires",
  CE5: "Power Front Passenger Seat with Back-Massager",
  PHC_03: "Ember Pearl-Coat Exterior Paint",
  TA_01: "Black / Steel Gray Interior Colors",
  XEE: "Fuel-Tank Skid-Plate Shield",
  SJJ: "Active Driving Assist System",
  XEU: "Front-Axle Skid-Plate",
  PHC: "Ember Pearl-Coat Exterior Paint/Black Clear-Coat Exterior Paint",
  CHE: "Deluxe Headliner",
  CAH: "Ventilated Rear Seats",
  MJX: "Painted Door Cladding",
  MHX: "Neutral Gray Exterior Accents",
  T7_01: "Tupelo/Black Interior Colors",
  TJE: "275/45R21Xl All-Season Tires",
  EC: "Palermo Leather Seats",
  AMP: "Obsidian Appearance Package",
  AFS: "Summit Reserve",
  CTX: "Palermo Leather Door Trim",
  MWZ: "Gloss-Black Roof Rails",
  MZ5: "Summit Reserve Badge",
  WJC: "21-Inch x 9.0-Inch Black Painted Aluminum Wheels",
  "27U": "Customer Preferred Package 27U",
  WJA: "21-Inch x 9.0-Inch Machined Face/Painted Alum Whls",
  ASW: "Luxury Tech Group V",
  T7_02: "Tupelo/Black Interior Colors",
  TKY: "265/50R20 Performance All-Season Tires",
  "27T": "Customer Preferred Package 27T",
  WHH: '20" x 8.5" Fully-Painted Aluminum Silver Wheels',
  "25R": "Customer Preferred Package 25R",
  WGM: "17-Inch x 7.5-Inch Machined Whls with Black Pockets",
  DHF: "4:1 Rock-Trac® Full Time 4WD System",
  WGQ: "17-Inch x 7.5-Inch Machined / Painted Black Wheels",
  "23R": "Customer Preferred Package 23R",
  Z1J: "GVW Rating - 5,350 Pounds",
  "22R": "Customer Preferred Package 22R",
  DMS: "4.88 Rear Axle Ratio",
  DSG: "Tru-Lok® Front Axle",
  "26R": "Customer Preferred Package 26R",
  AGV: "2nd-Row Seating Group",
  RCA: "McIntosh® MX950 Entertainment Sys with 19 Speakers",
  XNP: "Trailer-Hitch Line-Up Assist",
  TY4: "285/45R22XL BSW All-Season Tires",
  XAJ: "Side Distance Warning",
  TTH: "275/55R20 BSW All-Season Tires",
  CF5: "2nd-Row Captains Chairs with Power Tilt / Slide",
  DMD: "3.55 Rear Axle Ratio",
  CUQ: "Floor-Console with Cupholder",
  XQB: "Removable Rear Tow-Hook",
  GWM: "Tri-Pane Panoramic Sunroof",
  PCG_02: "River Rock Exterior Paint",
  MY7: "Power Deployable Running Boards",
  XNQ: "Trailer-Hitch Zoom",
  AAC: "Convenience Group",
  NMC: "Heavy-Duty Engine Cooling",
  EFH: "Hurricane Twin Turbo with Stop/Start",
  CUW: "Lockable Rear Underseat Storage",
  SJB: "Traffic Sign Recognition",
  D7_01: "Sea Salt / Black Interior Colors",
  CSD: "Foldable Cargo Shade",
  CYE: "7-Passenger Seating",
  XHQ: "Chrome Tow-Hooks",
  CLL: "Luxury Front and Rear Floor Mats",
  XPL: "Parallel and Perpendicular Park-Assist with Stop",
  CKK: "Reversible Cargo Mat",
  ANF: "Premium Group",
  DFR: "8-Speed Automatic 8HP75 Transmission with ERS",
  DMH: "3.92 Rear Axle Ratio",
  WPM: '22" Polished Aluminum Wheels w/ Black Noise Pockets',
  MWF: "Adjustable Roof-Rail Crossbars",
  MZB: '"Quadra Drive II" Badge',
  GL: "Nappa Leather-Trimmed Seats",
  XNM: "Drowsy Driver Detection",
  WRU: '20" Off-Road Aluminum Wheels',
  XHC: "Trailer-Brake Control",
  Z1C: "GVW Rating - 7,400 Pounds",
  "25E": "Customer Preferred Package 25E",
  WBK: '20" Machined Aluminum Wheels w/ Black Noise Pockets',
  NHZ: "Adaptive Cruise-Control with Stop and Go",
  JPZ: "Heated Second-Row Seats",
  WBA: "18-Inch Fully-Painted Satin Carbon Aluminum Wheels",
  TVL: "275/65R18 BSW All-Season Tires",
  XNW: "Active Lane-Management System",
  CLJ: "Rack Cargo Management System",
  D7_02: "Sea Salt / Black Interior Colors",
  Z1A: "GVW Rating - 5,800 Pounds",
  T7_03: "Tupelo/Black Interior Colors",
  CYF: "8-Passenger Seating",
  PNTTBL02: "Paint Table : Two Tone Paint Group",
  PCG: "River Rock Exterior Paint/Black Clear-Coat Exterior Paint",
  WSD: '22" Machined Aluminum Wheels w/ Black Noise Pockets',
  UL: "Quilted Palermo Leather-Trimmed Seats with Massage",
  XEC: "Black Tow-Hooks",
  MMR: "Gloss-Black Day Light Opening Moldings",
  EFC: "Hurricane Twin Turbo 510 with Stop/Start",
  XS4: "Black Interior Accents",
  WHX: '22" Polished Aluminum Wheels w/ Lights Out Pockets',
  MHY: "Piano-Black Exterior Accents",
  A6_02: "Blue Agave Interior Color",
  XT2: "Embossed-Metal Interior Accents",
  HEADER56: "Internal Options",
  PNTTBL03: "Paint Table : Secondary w/Series II & APA",
  Z1G: "GVW Rating - 7,800 Pounds",
  X7_04: "Global Black Interior Color",
  MXU: "Body-Color Roof",
  Z2E: "GVW Rating - 7,700 Pounds",
  UBQ: "Uconnect® 5 Nav with 12.0-Inch Touch Screen Display",
  CGL: "40/20/40 Pwr Tilt/Slide Rear Seat w/Manual Recline",
  "28W": "Customer Preferred Package 28W",
  A6_03: "Blue Agave Interior Color",
  PXJ_03: "Diamond Black Crystal Pearl-Coat Exterior Paint",
  XGP: "Front-Console Cooler",
  SL: "Palermo Leather-Trimmed Seats with Massage",
  Z6C: "GVW Rating - 7,950 Pounds",
  LSD: "Advanced Security Alert System",
  D7_03: "Sea Salt / Black Interior Colors",
  "28S": "Customer Preferred Package 28S",
  AAF: "Convenience Group",
  GAB: "Premium Color-Tinted Glass",
  ANG: "Premium Group II",
  WPZ: '22" Fully-Painted Satin-Carbon Aluminum Wheels',
  CCD: "Natural Walnut Wood Interior Accents",
  WPF: '22" Polished Aluminum Wheels w/ Luster Gray Pockets',
  RGE: "McIntosh® MX1375 Reference Entmt Sys w/ 23 Spkrs",
  X7_05: "Global Black Interior Color",
  XPR: "Rear Seat Monitoring Camera",
  WPV: '22" Tinted Polished Wheels with Black Insert',
  PNTTBL01: "Paint Table : Secondary w/Series II & APA & Obsidian",
  "28T": "Customer Preferred Package 28T",
  YCH: "Federal Emissions Order Code",
  X7_03: "Global Black Interior Color",
  WPA: '20" Machined Aluminum Wheels w/ Baltic Gray Pockets',
  WPY: '22" Wheels with Polished Painted Pockets',
  "23T": "Customer Preferred Package 23T",
  DKA: "2 Speed On-Demand Transfer Case",
  CBB: "3rd-Row Seat with 60/40 Power Fold/Recline",
  "25J": "Customer Preferred Package 25J",
  WPH: '22" Painted Gloss-Black Wheels',
  Z1B: "GVW Rating - 6,250 Pounds",
  WR1: '20" x 9.0" Gloss-Black Painted Aluminum Wheels',
  "25F": "Customer Preferred Package 25F",
  EZL: "5.7L V8 Engine with eTorque including Stop/Start",
  DMC: "3.21 Rear Axle Ratio",
  "22E": "Customer Preferred Package 22E",
  XHR: "400W Inverter",
  M9A: "Hex MOPAR Body Side Graphic",
  MVF: "American Flag Decals",
  DJF: "Dana M210 Wide Front Axle",
  BR1: "ABS 4-Wheel Heavy-Duty Disc Brakes with Front FNC",
  M9B: "Star MOPAR Body Side Graphic",
  "24F": "Customer Preferred Package 24F",
  SDW: "Normal Duty Plus Suspension",
  RSJ: "Wireless Speaker",
  XE9: "Transmission Skid-Plate",
  AM2: "Auxiliary Switch Group",
  TZB: "Bridgestone Brand Tires",
  X9B: "SiriusXM Radio Service",
  HT1_: "Black Freedom Top® 3-Piece Hard Top (fleet)",
  TZG: "BF Goodrich Brand Tires",
  MM2: "Black Molded-In-Color Fender Flares (2-Piece)",
  GFD: "Rear Sliding Window",
  XSF: "Freedom Edition Interior Accents",
  SFE: "Front Heavy-Duty Red-Accent Shock Absorbers",
  MM3: "Body-Color Fender Flares",
  JJ2: "97-MPH Vehicle Max-Speed Calibration",
  MXJ: "Texas Trail Tailgate & Hood Decals",
  HDB: "Supplemental Heater",
  MPQ: "Gladiator Fender Decal",
  ADM: "Freedom Edition Package",
  AL1: "Texas Trail",
  TTH_: "245/75R17 All-Terrain Tires (fleet)",
  XGS: "Cab Rock Rails",
  JAL: 'Cluster 7.0" TFT Color Display',
  CMD: "Trail Rail™ Management System",
  LL: "Leather-Trimmed Cloth Bucket Seats",
  M5C: "Freedom Package Decals",
  CSN: "Rear Armrest with Cupholder",
  X9H: "For More Info, Call 800-643-2112",
  JJ3: "110-MPH Vehicle Max Speed Calibration",
  JEX: "Power Tailgate Lock",
  SGE: "Rear Heavy-Duty Red-Accent Shock Absorbers",
  C1A: "#1 Seat Foam Cushion",
  AJQ: "Max Tow Package with 4.10 Axle Ratio",
  WFP: "17-Inch x 7.5-Inch Gloss-Black Aluminum Wheels",
  XBE: "Exterior 115V AC Outlet",
  MEG: "Rear Splash Guards by Mopar®",
  MG9: "Oscar Mike Badge",
  XMF: "Spray-In Bedliner by Mopar®",
  NF1: "19-Gallon Fuel Tank",
  XJC: "Locking Lug-Nuts",
  CSU: "Hard Tri-fold Tonneau Cover by Mopar®",
  CT6: "Soft Tri-Fold Tonneau Cover by Mopar®",
  M9C: "Retro MOPAR Body Side Graphic",
  SFA: "Sport Front Shock Absorbers",
  ML: "Premium McKinley-Trimmed Bucket Seats",
  AJ1_: "Jeep® Active Safety Group",
  SGA: "Sport Rear Shock Absorbers",
  ACP: "Capability Package",
  CVM: "Full-Length Floor Console with Premium Armrest",
  X9_02: "Black Interior Color",
  "24N": "Customer Preferred Package 24N",
  LCT: "LED Front Turn Signal and Parking Lamps",
  TV_02: "Black / Dark Saddle Interior Colors",
  WFA: "17-Inch x 7.5-Inch Low-Gloss Black Polished Wheels",
  TW2: "33-Inch LT285/70R17C All-Terrain Tires",
  WD3: "17-Inch x 7.5-Inch Low-Gloss Black Aluminum Wheels",
  "24D": "Customer Preferred Package 24D",
  MHD: "Black Hood Graphic by Mopar®",
  "23D": "Customer Preferred Package 23D",
  A5: "Premium Cloth Seats with Sport Bolsters",
  PL: "Leather-Trimmed Bucket Seats with Sport Bolsters",
  "24G": "Customer Preferred Package 24G",
  TDB: "255/70R18 BSW All-Terrain Tires",
  AEH: "Popular Equipment Package",
  WPT: "18-Inch x 7.5-Inch Granite Crystal Aluminum Wheels",
  C7: "Overland Cloth Bucket Seats",
  MGV: "Jeep Grille Hood Graphic by Mopar®",
  "24R": "Customer Preferred Package 24R",
  WFN: "17-Inch x 7.5-Inch Polished Black Aluminum Wheels",
  WFJ: "17-Inch x 7.5-Inch Granite Crystal Aluminum Wheels",
  "24B": "Customer Preferred Package 24B",
  WAA: "17-Inch x 7.5-Inch Black Steel Styled Wheels",
  HEADER57: "Internal Options",
  TQK: "245/75R17 All-Season Tires",
  MKN: "Splash Guards - Vehicle Set by Mopar®",
  "24S": "Customer Preferred Package 24S",
  ADC_: "Convenience Group (fleet)",
  WFS: "17-Inch x 7.5-Inch Tech-Silver Aluminum Wheels",
  HEADER58: "Internal Options",
  JL: "Leather-Trimmed Bucket Seats",
  YEP: "Manufacturer's Statement of Origin",
  WFW: "17-Inch x 7.5-Inch Black Aluminum Wheels",
  "24J": "Customer Preferred Package 24J",
  "24W": "Customer Preferred Package 24W",
  "24K": "Customer Preferred Package 24K",
};
